package br.com.palestrapizzaria.GUI;

import br.com.palestrapizzaria.DAO.ClienteDao;
import br.com.palestrapizzaria.DAO.FuncionarioDao;
import br.com.palestrapizzaria.entidade.Cliente;
import br.com.palestrapizzaria.entidade.Funcionario;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import br.com.palestrapizzaria.models.TableModelCliente;
import br.com.palestrapizzaria.models.TableModelFuncionario;

/**
 *
 * @author Geovani Pereira dos Santos
 */
public class TelaCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastro
     */
    private static TelaCadastro instancia;
    private TableModelCliente modelCliente = new TableModelCliente();
    private TableModelFuncionario modelFuncionario = new TableModelFuncionario();

    private ClienteDao cl_d = new ClienteDao();
    private FuncionarioDao fu_d = new FuncionarioDao();

    public TelaCadastro() {
        initComponents();
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        this.remove(titlePane);
        JTCliente.setModel(modelCliente);
        cbFun.setVisible(false);

    }

    public static TelaCadastro abrirJanela() {
        if (instancia == null) {
            instancia = new TelaCadastro();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtComplemto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTCliente = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkFun = new javax.swing.JCheckBox();
        cbFun = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbEscolhaBusca = new javax.swing.JComboBox<>();

        setBorder(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, 33));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 630, -1));

        jLabel2.setText("Bairro");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 292, -1));

        jLabel3.setText("Rua");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 71, -1, -1));
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 63, 300, -1));

        jLabel4.setText("Nº");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 121, -1, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        jLabel5.setText("Complemento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 121, -1, -1));
        jPanel1.add(txtComplemto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 113, 450, -1));

        jLabel6.setText("Telefone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, -1, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, -1));

        jLabel7.setText("CPF");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, -1));

        JTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 299, 688, 161));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 306, -1));

        jLabel8.setText("Buscar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        checkFun.setText("Funcionário");
        checkFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFunActionPerformed(evt);
            }
        });
        jPanel1.add(checkFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 30));

        cbFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizzaiolo", "Entregador", "Garçom", "Atendente", "Gerente", "Serviços Gerais", "Outros" }));
        cbFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFunActionPerformed(evt);
            }
        });
        jPanel1.add(cbFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, -1));

        btnCadastrar.setBackground(new java.awt.Color(0, 255, 102));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 90, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 90, -1));

        cbEscolhaBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Funcionario" }));
        cbEscolhaBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEscolhaBuscaItemStateChanged(evt);
            }
        });
        jPanel1.add(cbEscolhaBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed

    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (cbEscolhaBusca.getSelectedItem().toString().equals("Cliente")) {
            JTCliente.setModel(modelCliente);
            if (!txtBuscar.getText().equals("")) {
                modelCliente.setList(cl_d.buscar(txtBuscar.getText(), 8));
                JTCliente.repaint();
            } else {
                modelCliente.setList(new ArrayList<Cliente>());
                JTCliente.repaint();
            }
        } else {
            JTCliente.setModel(modelFuncionario);
            if (!txtBuscar.getText().equals("")) {
                modelFuncionario.setList(fu_d.buscar(txtBuscar.getText(), 8));
                JTCliente.repaint();
            } else {
                modelFuncionario.setList(new ArrayList<Funcionario>());
                JTCliente.repaint();
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void checkFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFunActionPerformed
        if (cbFun.isVisible()) {
            cbFun.setVisible(false);
        } else {
            cbFun.setVisible(true);
        }
    }//GEN-LAST:event_checkFunActionPerformed

    private void cbFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFunActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (checkFun.isSelected()) {
            FuncionarioDao fu_d = new FuncionarioDao();
            Funcionario f = new Funcionario();
            f.setNome(txtNome.getText());
            f.setCpf(Long.parseLong(txtCpf.getText()));
            f.setTelefone(Long.parseLong(txtTelefone.getText()));
            f.setBairro(txtBairro.getText());
            f.setComplemento(txtComplemto.getText());
            f.setNumero(Integer.parseInt(txtNumero.getText()));
            f.setRua(txtRua.getText());
            f.setCargo(cbFun.getSelectedItem().toString());

            fu_d.salvar(f);
        } else {

            ClienteDao cl_d = new ClienteDao();
            Cliente c = new Cliente();
            c.setNome(txtNome.getText());
            c.setCpf(Long.parseLong(txtCpf.getText()));
            c.setTelefone(Long.parseLong(txtTelefone.getText()));
            c.setBairro(txtBairro.getText());
            c.setComplemento(txtComplemto.getText());
            c.setNumero(Integer.parseInt(txtNumero.getText()));
            c.setRua(txtRua.getText());
            c.setAtivo(true);

            cl_d.salvar(c);
        }
        txtNome.setText("");
        txtCpf.setText("");
        txtTelefone.setText("");
        txtBairro.setText("");
        txtComplemto.setText("");
        txtNumero.setText("");
        txtRua.setText("");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JTCliente.getSelectedRow() != -1) {
            if (cbEscolhaBusca.getSelectedItem().toString().equals("Cliente")) {
                cl_d.excluir(modelCliente.getCliente(JTCliente.getSelectedRow()));
                modelCliente.setList(cl_d.buscar(txtBuscar.getText(), 8));
                JTCliente.repaint();
            } else {
                fu_d.excluir(modelFuncionario.getFuncionario(JTCliente.getSelectedRow()));
                modelFuncionario.setList(fu_d.buscar(txtBuscar.getText(), 8));
                JTCliente.repaint();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbEscolhaBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEscolhaBuscaItemStateChanged
        modelCliente.setList(new ArrayList<>());
        JTCliente.setModel(modelCliente);
    }//GEN-LAST:event_cbEscolhaBuscaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTCliente;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cbEscolhaBusca;
    private javax.swing.JComboBox<String> cbFun;
    private javax.swing.JCheckBox checkFun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtComplemto;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
