/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.palestrapizzaria.GUI;

import br.com.palestrapizzaria.DAO.ClienteDao;
import br.com.palestrapizzaria.DAO.EnderecoDao;
import br.com.palestrapizzaria.DAO.FuncionarioDao;
import br.com.palestrapizzaria.DAO.PedidoDao;
import br.com.palestrapizzaria.DAO.ProdutoDao;
import br.com.palestrapizzaria.entidade.Cliente;
import br.com.palestrapizzaria.entidade.Endereco;
import br.com.palestrapizzaria.entidade.Funcionario;
import br.com.palestrapizzaria.entidade.Item;
import br.com.palestrapizzaria.entidade.Pedido;
import br.com.palestrapizzaria.entidade.Produto;
import br.com.palestrapizzaria.models.TableModelCarrinho;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Geovani Pereira dos Santos
 */
public class TelaPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPedido
     */
    private static TelaPedido instancia;
    private TableModelCarrinho modelCarrinho = new TableModelCarrinho();
    private FuncionarioDao fu_d = new FuncionarioDao();
    private ClienteDao cl_d = new ClienteDao();
    private EnderecoDao en_d = new EnderecoDao();
    private PedidoDao pe_d = new PedidoDao();
    private static javax.swing.JDesktopPane TelasMdi;

    public TelaPedido() {
        initComponents();
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        this.remove(titlePane);
        JTCarrinho.setModel(modelCarrinho);

        //iniciando label de SubTotal
        ProdutoDao pr_d = new ProdutoDao();
        Produto p = pr_d.buscar(cbProd.getSelectedItem().toString());
        Double valor = p.getValor();
        Integer quantidade = Integer.parseInt(cbQuant.getSelectedItem().toString());
        Double subTotal = quantidade * valor;
        lblSubTotal.setText(subTotal.toString());
    }

    public static TelaPedido abrirJanela(javax.swing.JDesktopPane telaMDI) {
        if (instancia == null) {
            TelasMdi = telaMDI;
            instancia = new TelaPedido();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbQuant = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTCarrinho = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cbProd = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 23, 450, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Endereço");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Bairro");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        jLabel7.setText("Rua");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 200, -1));

        jLabel8.setText("Nº");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 24, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 70, -1));

        jLabel9.setText("Complemento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, 20));
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Adicionar Item");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel11.setText("Item");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel12.setText("Quantidade");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        cbQuant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbQuant.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbQuantComponentAdded(evt);
            }
        });
        cbQuant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQuantItemStateChanged(evt);
            }
        });
        cbQuant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbQuantMouseEntered(evt);
            }
        });
        jPanel1.add(cbQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 80, -1));

        jLabel13.setText("SubTotal");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        lblSubTotal.setText("0");
        jPanel1.add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        JTCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTCarrinho);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 744, 152));

        btnAddItem.setBackground(new java.awt.Color(0, 255, 102));
        btnAddItem.setText("Adicionar");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 103, -1));

        btnRemove.setBackground(new java.awt.Color(255, 102, 102));
        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 103, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 55, -1));

        lblTotal.setText("0");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        cbProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especial", "Peito de Peru", "Amoda", "Calabresa", "Mista" }));
        cbProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProdItemStateChanged(evt);
            }
        });
        jPanel1.add(cbProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 224, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 740, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 740, 10));

        jLabel1.setText("Telefone");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 170, -1));

        jLabel10.setText("Funcionario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alvaro Ernani" }));
        jPanel1.add(cbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        btnFinalizar.setBackground(new java.awt.Color(0, 255, 102));
        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(617, 617, 617)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        dialogButton = JOptionPane.showConfirmDialog(null, "Adicionar ao carrinho?", "Confirmação", dialogButton);

        TelaBuscaProduto t = new TelaBuscaProduto();
        t.setVisible(true);
        //TelasMdi.add(t);
                TelasMdi.removeAll();
        TelasMdi.add(t);
        TelasMdi.add(this);
        TelasMdi.repaint();
        
        Dimension x = new Dimension();
        x.setSize(20, 20);
                t.setMaximumSize(x);
        
        if (dialogButton == JOptionPane.YES_OPTION) {

            ProdutoDao pr_d = new ProdutoDao();
            Produto p = pr_d.buscar(cbProd.getSelectedItem().toString());
            Double valor = p.getValor();
            Integer quantidade = Integer.parseInt(cbQuant.getSelectedItem().toString());
            Double subTotal = quantidade * valor;
            lblSubTotal.setText(subTotal.toString());

            Double total = Double.parseDouble(lblTotal.getText());
            total += subTotal;
            lblTotal.setText(total.toString());

            Item item = new Item(p.getNome(), quantidade, valor);
            modelCarrinho.addRow(item);
        }

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void cbQuantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQuantItemStateChanged
        ProdutoDao pr_d = new ProdutoDao();
        Produto p = pr_d.buscar(cbProd.getSelectedItem().toString());
        Double valor = p.getValor();
        Integer quantidade = Integer.parseInt(cbQuant.getSelectedItem().toString());
        Double subTotal = quantidade * valor;
        lblSubTotal.setText(subTotal.toString());
    }//GEN-LAST:event_cbQuantItemStateChanged

    private void cbQuantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbQuantMouseEntered
    }//GEN-LAST:event_cbQuantMouseEntered

    private void cbQuantComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbQuantComponentAdded
    }//GEN-LAST:event_cbQuantComponentAdded

    private void cbProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProdItemStateChanged
        ProdutoDao pr_d = new ProdutoDao();
        Produto p = pr_d.buscar(cbProd.getSelectedItem().toString());
        Double valor = p.getValor();
        Integer quantidade = Integer.parseInt(cbQuant.getSelectedItem().toString());
        Double subTotal = quantidade * valor;
        lblSubTotal.setText(subTotal.toString());
    }//GEN-LAST:event_cbProdItemStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (JTCarrinho.getSelectedRow() != -1) {
            Item it = modelCarrinho.getItem(JTCarrinho.getSelectedRow());

            Double total = Double.parseDouble(lblTotal.getText());
            total -= it.getTotal();
            lblTotal.setText(total.toString());

            modelCarrinho.removeRow(JTCarrinho.getSelectedRow());
            System.out.println(modelCarrinho.getRowCount());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        Cliente cli = new Cliente();
        Funcionario fun = fu_d.buscar(cbFuncionario.getSelectedItem().toString());
        Pedido ped = new Pedido();
        Endereco end = new Endereco();
        
        cli.setNome(txtNome.getText());
        cli.setBairro(txtBairro.getText());
        cli.setComplemento(txtComplemento.getText());
        cli.setNumero(Integer.parseInt(txtNumero.getText()));
        cli.setRua(txtRua.getText());
        cli.setTelefone(Long.parseLong(txtTelefone.getText()));
        cli.setAtivo(true);
        
        //cl_d.salvarSemCad(cli);
        //cli = cl_d.buscarSemCad(cli.getNome());
        
        end.setBairro(txtBairro.getText());
        end.setComplemento(txtComplemento.getText());
        end.setNumero(Integer.parseInt(txtNumero.getText()));
        end.setRua(txtRua.getText());
        
        //en_d.salvar(end);
        //end = en_d.buscarEnd(end);
        
        ped.setAtendimento("Balcao");
        ped.setCliente(cli);
        ped.setFuncionario(fun);
        ped.setEntrega(end);
        ped.setListItem(modelCarrinho.getList());
        
        //pe_d.salvar(ped);
        
        
        
        
        
    }//GEN-LAST:event_btnFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTCarrinho;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JComboBox<String> cbProd;
    private javax.swing.JComboBox<String> cbQuant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
